# Generated by Django 3.2.6 on 2022-09-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0002_jobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='company_id',
            new_name='company',
        ),
    ]
