# Generated by Django 3.2.6 on 2022-09-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Portal', '0003_rename_company_id_jobs_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
